# Generated by Django 4.2.6 on 2023-10-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
