# Generated by Django 4.2.6 on 2023-10-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0005_alter_ticket_author_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
