# Generated by Django 4.2.6 on 2023-10-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0006_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_devs',
            new_name='assign_devs',
        ),
    ]
