# Generated by Django 4.2.6 on 2023-10-24 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtrackerapp', '0007_rename_assigned_devs_ticket_assign_devs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assign_devs',
            field=models.ManyToManyField(blank=True, related_name='devs', to=settings.AUTH_USER_MODEL),
        ),
    ]
