# Generated by Django 4.2.6 on 2023-10-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0008_alter_ticket_assign_devs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assign_devs',
            new_name='assign_members',
        ),
    ]
